### ISSUE TITLE
npm发布组件的那个链接好像挂了

### ISSUE THREAD

**Issue by Linnanli** [zyy782/yuanyuan.github.io#5]

**Comment by zyy782** [comment]
最近太忙了 忘记推送了 现在o的k了&nbsp;&nbsp;




张媛媛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zyy782/yuanyuan.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月7日(星期二) 下午3:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zyy782/yuanyuan.github.io] npm发布组件的那个链接好像挂了 (Issue #5)

**Comment by Linnanli** [comment]
![image](https://user-images.githubusercontent.com/17219492/222617069-7d72f9d1-ff0c-451b-ae0b-ab3d9773d046.png)
issues完成后可以关闭掉
